config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :forum_threads do
    resources :forum_posts, module: :forum_threads
  end

  resources :users do
    collection do
      post :import
    end
  end

  root 'forum_threads#index'

  default_url_options :host => "example.com"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum_post.rb
# == Schema Information
#
# Table name: forum_posts
#
#  id              :integer          not null, primary key
#  forum_thread_id :integer
#  user_id         :integer
#  body            :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class ForumPost < ApplicationRecord
  belongs_to :forum_thread
  belongs_to :user

  validates :body, presence: true

  # overwriting original belongs_to method 
  def user
    User.unscoped { super }
  end

  def send_notifications!
    # Get all uniq users, except current user
    users = forum_thread.users.uniq - [user]
    # Send email to each of them
    users.each do |user|
      NotificationMailer.forum_post_notification(user, self).deliver_later
    end
  end
end

app/models/forum_thread.rb
# == Schema Information
#
# Table name: forum_threads
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  subject    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#
# Indexes
#
#  index_forum_threads_on_deleted_at  (deleted_at)
#

class ForumThread < ApplicationRecord
  acts_as_paranoid

  belongs_to :user
  has_many :forum_posts
  has_many :users, through: :forum_posts

  accepts_nested_attributes_for :forum_posts

  validates :subject, presence: true
  validates_associated :forum_posts
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  deleted_at             :datetime
#  first_name             :string
#  last_name              :string
#
# Indexes
#
#  index_users_on_deleted_at            (deleted_at)
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :forum_threads
  has_many :forum_posts

  def self.assign_from_row(row)
    user = User.where(email: row[:email]).first_or_initialize
    user.assign_attributes row.to_hash.slice(:first_name, :last_name)
    user
  end

  def self.to_csv
    attributes = %w{id email first_name last_name}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr)}
      end
    end
  end

  def name
    if deleted_at?
      'Deleted user'
    else
      "#{first_name} #{last_name}"
    end
  end
end

app/models/user/import.rb
class User::Import
  include ActiveModel::Model

  attr_accessor :file, :imported_count

  def process!
    @imported_count = 0
    CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
      user = User.assign_from_row(row)
      if user.save
        @imported_count += 1
      else
        errors.add(:base, "Line #{$.} - #{user.errors.full_messages.join(",")}")
      end
    end
  end

  def save
    process!
    errors.none?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/forum_threads/forum_posts_controller.rb
class ForumThread::ForumPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_forum_thread

  def create
    @forum_post = @forum_thread.forum_posts.new forum_post_params
    @forum_post.user = current_user

    if @forum_post.save
      @forum_post.send_notifications!
      redirect_to forum_thread_path(@forum_thread, anchor: "forum_post_#{@forum_post.id}"), notice: 'Successfully posted!'
    else
      redirect_to @forum_thread, alert: 'Unable to save your post!'
    end
  end

  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:forum_thread_id])
    end

    def forum_post_params
      params.require(:forum_post).permit(:body)
    end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_forum_thread, except: [:index, :new, :create]

  def index
    @q = ForumThread.search(params[:q])
    @forum_threads = @q.result(distinct: true)
  end

  def show
  end

  def new
    @forum_thread = ForumThread.new
    @forum_thread.forum_posts.new
  end

  def create
    @forum_thread = current_user.forum_threads.new forum_thread_params
    @forum_thread.forum_posts.first.user_id = current_user.id

    if @forum_thread.save
      redirect_to @forum_thread
    else
      render action: :new
    end
  end

  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:id])
    end

    def forum_thread_params
      params.require(:forum_thread).permit(:subject, forum_posts_attributes: [:body])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @import = User::Import.new

    respond_to do |format|
      format.html
      format.csv { send_data @users.to_csv }
    end
  end

  def import
    @import = User::Import.new user_import_params
    if @import.save
      redirect_to users_path, notice: "Imported #{@import.imported_count} users"
    else
      @users = User.all
      flash[:alert] = "There were #{@import.errors.count} errors in your csv file."
      render action: :index
    end
  end

  private

  def user_import_params
    params.require(:user_import).permit(:file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
  def markdownify(content)
    pipeline_context = { gfm: true, asset_root: "https://a248.e.akamai.net/assets.github.com/images/icons"}
    pipeline = HTML::Pipeline.new [
      HTML::Pipeline::MarkdownFilter,
      HTML::Pipeline::EmojiFilter,
      HTML::Pipeline::SanitizationFilter
    ], pipeline_context
    pipeline.call(content)[:output].to_s.html_safe
  end
end

app/views/forum_posts/_forum_post.html.erb
<%= div_for forum_post do %>
  {{!-- check strfti.me to be sure in time settings  --}}
  <p class="text-muted">Posted by <%= forum_post.user.email %> <%= local_time_ago forum_post.created_at%></p>
  <p><%= markdownify forum_post.body %></p>
<% end %>

app/views/forum_threads/_form.html.erb
<%= form_for @forum_thread do |f| %>
  <div class="form-group">
    <%= f.text_field :subject, placeholder: 'Subject', class: 'form-control' %>
  </div>

  <%= f.fields_for :forum_posts do |p| %>
    <div class="form-group">
      <%= p.text_area :body, placeholder: 'Add a comment', rows: 10, class: 'form-control' %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/forum_threads/_forum_thread.html.erb
<%= link_to forum_thread do %>
  <h3><%= forum_thread.subject %></h3>
<% end %>

app/views/forum_threads/edit.html.erb
<h1>Editing forum_thread</h1>

<%= render 'form' %>

<%= link_to 'Show', @forum_thread %> |
<%= link_to 'Back', forum_threads_path %>

app/views/forum_threads/index.html.erb
<div class="container">
  <%= link_to "New Thread", new_forum_thread_path, class: "btn btn-success float-xs-right" %>

  <div class="float-xs-right" style="margin-right: 10px">
    <%= search_form_for @q, html: {class: 'form-inline'} do |f| %>
      <%= f.search_field :subject_or_forum_posts_body_cont, placeholder: 'Search ...', class: 'form-control' %>
    <% end %>
  </div>

  <h1 class="page-header">Forum Threads</h1>
  <%= render @forum_threads %>
</div>

app/views/forum_threads/new.html.erb
<h1>New Thread</h1>
<%= render 'form' %>

app/views/forum_threads/show.html.erb
<div class="container">
  <h1><%= @forum_thread.subject %></h1>
  <p class="text-muted">Created by <%= @forum_thread.user.email %></p>
  <%= render @forum_thread.forum_posts %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-faded">
  <div class="container">
    <div class="nav navbar-nav">
      <%= link_to 'Forum', root_path, class: 'navbar-brand' %>
      <div class="float-xs-right">
      <% if user_signed_in? %>
        <%= link_to 'Account', edit_user_registration_path, class: 'btn btn-secondary' %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-secondary' %>
      <% else %>
        <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-secondary' %>
        <%= link_to 'Login', new_user_session_path, class: 'btn btn-secondary' %>
      <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% if notice %><div class="alert alert-success" role="alert"><%= notice %></div><% end %>
    <% if alert %><div class="alert alert-warning" role="alert"><%= alert %></div><% end %>

    <div class="container page-margin">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-striped table-bordered">
  <thead>
    <th>Id</th>
    <th>Name</th>
    <th>Email</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= form_for @import, url: import_users_path, multipart: true do |f| %>
  <% if @import.erros.any? %>
    <div class="alert alert-error">
      <% @import.errors.full_messages.each do |msg| %>
        <div><%= msg %></div>
      <% end %>
    </div>
  <% end %>

  <%= f.file_field :file %>
  <%= f.submit 'Upload' %>
<% end %>